window.LSKSync = (() => {
  const DB='anvi-mitra-erp-sync'; const STORE='outbox'; const META='meta'; let dbPromise;
  const db=()=>dbPromise ||= new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'clientId'});if(!d.objectStoreNames.contains(META))d.createObjectStore(META,{keyPath:'key'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
  const tx=async(store,mode,fn)=>{const d=await db();return new Promise((resolve,reject)=>{const t=d.transaction(store,mode),s=t.objectStore(store);let value;try{value=fn(s)}catch(e){reject(e);return}t.oncomplete=()=>resolve(value);t.onerror=()=>reject(t.error)})};
  async function meta(key,fallback){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction(META,'readonly').objectStore(META).get(key);r.onsuccess=()=>resolve(r.result?.value??fallback);r.onerror=()=>reject(r.error)})}
  async function setMeta(key,value){return tx(META,'readwrite',s=>s.put({key,value}))}
  async function enqueue(change){const item={clientId:change.clientId||crypto.randomUUID(),entityType:String(change.entityType||''),entityId:change.entityId||null,operation:change.operation,payload:change.payload||{},baseCursor:Number(change.baseCursor||0),createdAt:new Date().toISOString()};if(!item.entityType||!['create','update','delete'].includes(item.operation))throw new Error('Invalid sync change');await tx(STORE,'readwrite',s=>s.put(item));await flush();return item.clientId}
  async function all(){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction(STORE,'readonly').objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
  async function remove(ids){if(!ids.length)return;return tx(STORE,'readwrite',s=>ids.forEach(id=>s.delete(id)))}
  async function register(deviceKey,deviceName='Web browser',platform='web'){return api('/api/sync/device',{method:'POST',body:JSON.stringify({deviceKey,deviceName,platform})})}
  async function flush(){if(!navigator.onLine)return {offline:true};const deviceKey=await meta('deviceKey',null);if(!deviceKey)return {registered:false};const pending=await all();if(!pending.length)return {sent:0};try{const r=await api('/api/sync/push',{method:'POST',body:JSON.stringify({deviceKey,changes:pending.slice(0,200)})});const done=new Set((r.accepted||[]).map(x=>x.clientId).filter(Boolean));await remove([...done]);for(const c of r.conflicts||[])await setMeta('conflict:'+c.clientId,c);return {sent:done.size,conflicts:(r.conflicts||[]).length}}catch(e){return {error:e.message,pending:pending.length}}}
  async function pull(){if(!navigator.onLine)return {offline:true};const deviceKey=await meta('deviceKey',null);if(!deviceKey)return {registered:false};const cursor=Number(await meta('cursor',0));const r=await api('/api/sync/changes?deviceKey='+encodeURIComponent(deviceKey)+'&cursor='+cursor+'&limit=250');await setMeta('cursor',Number(r.cursor||cursor));window.dispatchEvent(new CustomEvent('lsk:sync-changes',{detail:r.changes||[]}));return r}
  async function sync(){const pushed=await flush();const pulled=await pull();window.dispatchEvent(new CustomEvent('lsk:sync-status',{detail:{pushed,pulled,online:navigator.onLine}}));return {pushed,pulled}}
  async function api(path,options={}){if(!window.LSKERP?.request)throw new Error('LSKERP API client is not loaded');return LSKERP.request(path,options)}
  window.addEventListener('online',()=>sync());
  return {db,meta,setMeta,enqueue,all,register,flush,pull,sync};
})();
