const fs = require('fs');
const path = require('path');
const assert = require('assert');

const organization = fs.readFileSync(path.join(__dirname, '..', 'src', 'organization.js'), 'utf8');
const platformSchools = fs.readFileSync(path.join(__dirname, '..', 'src', 'platform_school_management.js'), 'utf8');
const auth = fs.readFileSync(path.join(__dirname, '..', 'src', 'auth.js'), 'utf8');
const schoolUi = fs.readFileSync(path.join(__dirname, '..', 'web', 'super-admin', 'schools.html'), 'utf8');

assert(organization.includes("app.get('/api/public/school-config'"));
assert(organization.includes("app.post('/api/platform/schools'"));
assert(platformSchools.includes("app.patch('/api/platform/schools/:id'"));
assert(platformSchools.includes("app.post('/api/platform/schools/:id/logo'"));
assert(platformSchools.includes("app.get('/api/platform/schools/:id'"));
assert(organization.includes("await hashPassword(adminPassword)"));
assert(organization.includes("adminEmail"));
assert(organization.includes("adminPhone"));
assert(platformSchools.includes("hashPassword"));
assert(organization.includes("mobile_app_configs"));
assert(platformSchools.includes("school_settings"));
assert(organization.includes("school_settings"));
assert(organization.includes("branches"));
assert(organization.includes("INSERT INTO users"));
assert(organization.includes("password_hash,role,status) VALUES($1,$2,$3,$4,$5,'admin','active')"), 'Administrator role/status provisioning contract missing');
assert(auth.includes("schoolId"));
assert(auth.includes("branchId"));
assert(auth.includes("resolveBranch"));
assert(schoolUi.includes("School Management"));
assert(schoolUi.includes("Add School"));
assert(schoolUi.includes("Create School + Admin"));
assert(schoolUi.includes("Admin email"));
assert(schoolUi.includes("Admin password"));
assert(schoolUi.includes("/api/platform/schools"));
assert(schoolUi.includes("/api/platform/schools/"));
assert(schoolUi.includes("navigator.onLine"));
assert(schoolUi.includes("cached data and pending changes"));
console.log('ERP school provisioning/UI contract checks: PASS');
