import 'package:flutter/material.dart';
import 'dashboard_service.dart';

class DriverDashboard extends StatefulWidget { const DriverDashboard({super.key}); @override State<DriverDashboard> createState()=>_DriverDashboardState(); }
class _DriverDashboardState extends State<DriverDashboard> {
 final s=DashboardService(); bool loading=true; String? error; Map<String,dynamic> d={}; Map<String,dynamic> trip={};
 @override void initState(){super.initState();load();}
 Future<void> load() async { try { final x=await s.driverOverview(); if(mounted)setState((){d=x;trip=Map<String,dynamic>.from((x['driver'] as Map?)??{});loading=false;}); } catch(e){if(mounted)setState((){error=e.toString();loading=false;});} }
 Future<void> action(Future<Map<String,dynamic>> Function() fn) async { try { await fn(); await load(); if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Trip status updated'))); } catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));} }
 @override Widget build(BuildContext c){if(loading)return const Center(child:CircularProgressIndicator());if(error!=null)return Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text(error!),FilledButton(onPressed:load,child:const Text('Retry'))])); final id=trip['tripId']?.toString(); final status=trip['tripStatus']?.toString()??'planned'; return RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:[Text('Driver Dashboard',style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:14),Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.directions_bus)),title:Text(trip['registrationNo']?.toString()??'Vehicle not assigned'),subtitle:Text('${trip['vehicleType']??'School transport'} • ${trip['routeName']??'Route not assigned'}'))),Row(children:[Expanded(child:_stat(c,'Students',trip['studentCount']??0,Icons.groups)),Expanded(child:_stat(c,'Trip',status,Icons.route))]),const SizedBox(height:12),if(id!=null)...[_tripAction(c,id,status)],Card(child:ListTile(leading:const Icon(Icons.location_on),title:const Text('Today’s Route'),subtitle:Text(trip['routeName']?.toString()??'No route assigned'))),Card(child:ListTile(leading:const Icon(Icons.security),title:const Text('Safety'),subtitle:const Text('Boarding and drop events are recorded securely.')))])); }
 Widget _tripAction(BuildContext c,String id,String status){if(status=='planned')return FilledButton.icon(onPressed:()=>action(()=>s.startTrip(id)),icon:const Icon(Icons.play_arrow),label:const Text('START TRIP'));if(status=='started')return FilledButton.icon(onPressed:()=>action(()=>s.completeTrip(id)),icon:const Icon(Icons.flag),label:const Text('COMPLETE TRIP'));return Card(child:ListTile(leading:const Icon(Icons.check_circle),title:Text(status=='completed'?'Trip Completed':'Trip $status'),subtitle:const Text('Today’s trip control is complete.')));}
 Widget _stat(BuildContext c,String t,Object v,IconData i)=>TweenAnimationBuilder<double>(tween:Tween(begin:0,end:1),duration:const Duration(milliseconds:500),builder:(x,n,ch)=>Transform.scale(scale:.94+.06*n,child:Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(i),const SizedBox(height:6),Text('$v',style:Theme.of(c).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w800)),Text(t)])))));
}
