import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';
import 'app_config.dart';
import 'offline_sync.dart';

void main(){WidgetsFlutterBinding.ensureInitialized();runApp(const AnviMitraApp());}
class AnviMitraApp extends StatelessWidget{const AnviMitraApp({super.key});@override Widget build(BuildContext context)=>MaterialApp(title:AppConfig.appName,debugShowCheckedModeBanner:false,theme:ThemeData(colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xFF4F46E5)),useMaterial3:true),home:const LoginPage());}
class LoginPage extends StatefulWidget{const LoginPage({super.key});@override State<LoginPage> createState()=>_LoginPageState();}
class _LoginPageState extends State<LoginPage>{
 final school=TextEditingController(text:AppConfig.schoolCode),login=TextEditingController(),password=TextEditingController(); bool busy=false; String? error;
 @override void dispose(){school.dispose();login.dispose();password.dispose();super.dispose();}
 Future<void> submit() async{setState((){busy=true;error=null;});try{if(school.text.trim().isEmpty||login.text.trim().isEmpty||password.text.isEmpty)throw Exception('School code, login and password are required');final r=await http.post(Uri.parse('${AppConfig.apiBaseUrl}/api/auth/login'),headers:{'Content-Type':'application/json','Accept':'application/json'},body:jsonEncode({'schoolCode':school.text.trim(),'login':login.text.trim(),'password':password.text}));final d=jsonDecode(r.body.isEmpty?'{}':r.body);if(r.statusCode<200||r.statusCode>=300)throw Exception(d is Map&&d['error']!=null?d['error']:'Login failed (${r.statusCode})');final token=d['accessToken']?.toString();if(token==null||token.isEmpty)throw Exception('Login response did not contain an access token');final prefs=await SharedPreferences.getInstance();await prefs.setString('erp_access_token',token);await prefs.setString('erp_user',jsonEncode(d['user']??{}));await OfflineSyncService.instance.initialize(accessToken:token);if(!mounted)return;Navigator.of(context).pushReplacement(MaterialPageRoute(builder:(_)=>const HomePage()));}catch(e){if(mounted)setState(()=>error=e.toString().replaceFirst('Exception: ',''));}finally{if(mounted)setState(()=>busy=false);}}
 @override Widget build(BuildContext context)=>Scaffold(body:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:430),child:Card(child:Padding(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Icon(Icons.school_rounded,size:58),const SizedBox(height:14),Text(AppConfig.appName,textAlign:TextAlign.center,style:TextStyle(fontSize:24,fontWeight:FontWeight.w800)),const SizedBox(height:6),const Text('One app for school staff, parents, students and drivers',textAlign:TextAlign.center),const SizedBox(height:24),TextField(controller:school,decoration:const InputDecoration(labelText:'School Code',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:login,decoration:const InputDecoration(labelText:'Email / Phone',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'Password',border:OutlineInputBorder())),if(error!=null)Padding(padding:const EdgeInsets.only(top:12),child:Text(error!,style:TextStyle(color:Theme.of(context).colorScheme.error))),const SizedBox(height:18),FilledButton(onPressed:busy?null:submit,child:Text(busy?'Signing in…':'Sign in')),const SizedBox(height:10),Text('API: ${AppConfig.apiBaseUrl}',textAlign:TextAlign.center,style:Theme.of(context).textTheme.bodySmall)]))))))));}
}
class HomePage extends StatefulWidget{const HomePage({super.key});@override State<HomePage> createState()=>_HomePageState();}
class _HomePageState extends State<HomePage>{int pending=0;String status='Ready';Map<String,dynamic>? overview;bool loadingOverview=true;
 @override void initState(){super.initState();refresh();loadOverview();}
 Future<void> refresh()async{final c=await OfflineSyncService.instance.pendingCount();if(mounted)setState(()=>pending=c);}
 Future<Map<String,dynamic>> api(String path)async{final prefs=await SharedPreferences.getInstance();final token=prefs.getString('erp_access_token')??'';final r=await http.get(Uri.parse('${AppConfig.apiBaseUrl}$path'),headers:{'Authorization':'Bearer $token','Accept':'application/json'});final d=jsonDecode(r.body.isEmpty?'{}':r.body);if(r.statusCode<200||r.statusCode>=300)throw Exception(d is Map&&d['error']!=null?d['error']:'Request failed');return Map<String,dynamic>.from(d as Map);}
 Future<void> loadOverview()async{try{final prefs=await SharedPreferences.getInstance();final raw=prefs.getString('erp_user');final u=raw==null?<String,dynamic>{}:Map<String,dynamic>.from(jsonDecode(raw) as Map);final role='${u['role']??''}'.toLowerCase();Map<String,dynamic> data={};if(role=='teacher')data=await api('/api/portal/me/teacher-overview');else if(role=='student')data=await api('/api/portal/me/student-overview');else if({'super_admin','principal','admin'}.contains(role))data=await api('/api/portal/me/admin-overview');else if(role=='parent')data=await api('/api/portal/me/students');if(mounted)setState((){overview=data;loadingOverview=false;});}catch(_){if(mounted)setState(()=>loadingOverview=false);}}
 Future<void> sync()async{setState(()=>status='Syncing…');try{await OfflineSyncService.instance.syncNow();await refresh();await loadOverview();if(mounted)setState(()=>status='Synced successfully');}catch(_){if(mounted)setState(()=>status='Offline / sync pending');}}
 Widget stat(String label,String value)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(label,style:Theme.of(context).textTheme.bodySmall),const SizedBox(height:5),Text(value,style:const TextStyle(fontSize:24,fontWeight:FontWeight.w800))])));
 List<Widget> overviewCards(){final u=overview??{};if(u['stats'] is Map){final s=Map<String,dynamic>.from(u['stats']);return[stat('Students','${s['studentCount']??0}'),stat('Teachers','${s['teacherCount']??0}'),stat('Attendance','${s['attendancePercent']??0}%'),stat('Outstanding','₹${s['outstanding']??0}')];}if(u['sections'] is List){final rows=u['sections'] as List;return[stat('Assigned sections','${rows.length}'),stat('Students','${u['studentCount']??0}'),stat('Subjects','${rows.map((e)=>e is Map?e['subjectName']:null).where((e)=>e!=null).toSet().length}'),stat('Access','Permission based')];}if(u['student'] is Map){final s=Map<String,dynamic>.from(u['student']);final a=u['attendance'] is Map?Map<String,dynamic>.from(u['attendance'] as Map):{};return[stat('Class','${s['className']??'—'}'),stat('Section','${s['sectionName']??'—'}'),stat('Attendance','${a['attendancePercent']??0}%'),stat('Fee due','₹${u['outstanding']??0}')];}if(u['students'] is List)return[stat('Children','${(u['students'] as List).length}'),stat('Sync queue','$pending'),stat('Connection',status),stat('School app','Active')];return[stat('Sync queue','$pending'),stat('Connection',status),stat('ERP','Connected'),stat('Role','Unified')];}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(AppConfig.appName),actions:[IconButton(onPressed:sync,icon:const Icon(Icons.sync))]),body:RefreshIndicator(onRefresh:sync,child:ListView(padding:const EdgeInsets.all(16),children:[Card(child:ListTile(leading:const Icon(Icons.cloud_done),title:const Text('ERP connection'),subtitle:Text(status),trailing:Text('$pending pending'))),if(loadingOverview)const Padding(padding:EdgeInsets.all(20),child:Center(child:CircularProgressIndicator())) else ...[GridView.count(crossAxisCount:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisSpacing:8,mainAxisSpacing:8,childAspectRatio:1.7,children:overviewCards()),const SizedBox(height:8)],const _ModuleCard(icon:Icons.people,title:'Students & Enrollments',text:'Student profiles, admissions and class enrollment.'),const _ModuleCard(icon:Icons.fact_check,title:'Attendance',text:'Role-aware attendance and class records.'),const _ModuleCard(icon:Icons.edit_note,title:'Exams & Marks',text:'Teachers can edit only their permitted class/subject records.'),const _ModuleCard(icon:Icons.receipt_long,title:'Fees',text:'Fee invoices, payments and outstanding records.'),const _ModuleCard(icon:Icons.notifications_active,title:'Notifications',text:'School updates with offline cache and automatic sync.') ]));}}
class _ModuleCard extends StatelessWidget{final IconData icon;final String title;final String text;const _ModuleCard({required this.icon,required this.title,required this.text});@override Widget build(BuildContext context)=>Card(child:ListTile(leading:Icon(icon),title:Text(title,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(text)));}
