import 'dart:async';
import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';
import 'app_config.dart';

class OfflineSyncService {
  OfflineSyncService._();
  static final OfflineSyncService instance = OfflineSyncService._();
  static const _deviceKeyPref='erp_sync_device_key',_cursorPref='erp_sync_cursor',_outboxPref='erp_sync_outbox',_conflictsPref='erp_sync_conflicts',_cachePrefix='erp_sync_cache_';
  SharedPreferences? _prefs; String? _accessToken; Timer? _autoSyncTimer; bool _syncing=false;
  Future<void> initialize({required String accessToken}) async {_prefs??=await SharedPreferences.getInstance();_accessToken=accessToken;await _ensureDevice().catchError((_){});_autoSyncTimer?.cancel();_autoSyncTimer=Timer.periodic(const Duration(minutes:1),(_)=>syncNow().catchError((_){}));}
  void dispose(){_autoSyncTimer?.cancel();_autoSyncTimer=null;}
  Future<String> _deviceKey() async {final p=_prefs??=await SharedPreferences.getInstance();final e=p.getString(_deviceKeyPref);if(e!=null&&e.isNotEmpty)return e;final v='${DateTime.now().microsecondsSinceEpoch}-${identityHashCode(this)}';await p.setString(_deviceKeyPref,v);return v;}
  Future<Map<String,dynamic>> _request(String path,{String method='GET',Map<String,dynamic>? body}) async {final token=_accessToken;if(token==null||token.isEmpty)throw StateError('Offline sync is not initialized');final uri=Uri.parse('${AppConfig.apiBaseUrl}$path');final response=await(method=='POST'?http.post(uri,headers:{'Authorization':'Bearer $token','Content-Type':'application/json'},body:jsonEncode(body??{})):http.get(uri,headers:{'Authorization':'Bearer $token'}));final data=jsonDecode(response.body.isEmpty?'{}':response.body);if(response.statusCode<200||response.statusCode>=300)throw Exception(data is Map&&data['error']!=null?data['error']:'Sync request failed (${response.statusCode})');return Map<String,dynamic>.from(data as Map);}
  Future<void> _ensureDevice() async {final key=await _deviceKey();final platform=defaultTargetPlatform.toString().split('.').last;await _request('/api/sync/device',method:'POST',body:{'deviceKey':key,'deviceName':platform,'platform':platform});}
  Future<List<Map<String,dynamic>>> _outbox() async {final p=_prefs??=await SharedPreferences.getInstance();final raw=p.getString(_outboxPref);if(raw==null||raw.isEmpty)return[];final d=jsonDecode(raw);if(d is! List)return[];return d.map((e)=>Map<String,dynamic>.from(e as Map)).toList();}
  Future<void> _saveOutbox(List<Map<String,dynamic>> items) async{final p=_prefs??=await SharedPreferences.getInstance();await p.setString(_outboxPref,jsonEncode(items));}
  Future<List<Map<String,dynamic>>> _conflicts() async{final p=_prefs??=await SharedPreferences.getInstance();final raw=p.getString(_conflictsPref);if(raw==null||raw.isEmpty)return[];final d=jsonDecode(raw);if(d is! List)return[];return d.map((e)=>Map<String,dynamic>.from(e as Map)).toList();}
  Future<void> _saveConflicts(List<Map<String,dynamic>> items) async{final p=_prefs??=await SharedPreferences.getInstance();await p.setString(_conflictsPref,jsonEncode(items));}
  Future<void> queueChange({required String entityType,required String operation,String? entityId,Map<String,dynamic> payload=const{}}) async{if(!{'create','update','delete'}.contains(operation))throw ArgumentError('operation must be create, update or delete');final items=await _outbox();final clientId='${DateTime.now().microsecondsSinceEpoch}-${items.length}';final p=_prefs??=await SharedPreferences.getInstance();final cursor=p.getInt(_cursorPref)??0;items.add({'clientId':clientId,'entityType':entityType,'entityId':entityId,'operation':operation,'payload':payload,'baseCursor':cursor,'queuedAt':DateTime.now().toIso8601String()});await _saveOutbox(items);}
  Future<int> pendingCount() async=>(await _outbox()).length; Future<int> conflictCount() async=>(await _conflicts()).length; Future<List<Map<String,dynamic>>> pendingConflicts()=>_conflicts();
  Future<List<Map<String,dynamic>>> refreshConflicts() async{final r=await _request('/api/sync/conflicts?resolution=pending');final raw=r['conflicts'];final server=raw is List?raw.map((e)=>Map<String,dynamic>.from(e as Map)).toList():<Map<String,dynamic>>[];final local=await _conflicts();final merged=<String,Map<String,dynamic>>{};for(final c in local){final id=c['conflictId']?.toString()??c['id']?.toString();if(id!=null)merged[id]=c;}for(final c in server){final id=c['id']?.toString();if(id!=null)merged[id]={...?merged[id],...c};}await _saveConflicts(merged.values.toList());return merged.values.toList();}
  Future<Map<String,dynamic>> resolveConflict({required String conflictId,required String resolution,Map<String,dynamic>? mergedPayload,String note=''}) async{if(!{'server_wins','local_wins','merged'}.contains(resolution))throw ArgumentError('resolution must be server_wins, local_wins or merged');if(resolution=='merged'&&mergedPayload==null)throw ArgumentError('mergedPayload is required for merged resolution');final r=await _request('/api/sync/conflicts/${Uri.encodeComponent(conflictId)}/resolve',method:'POST',body:{'resolution':resolution,'mergedPayload':mergedPayload,'note':note});final current=await _conflicts();current.removeWhere((c)=>c['conflictId']?.toString()==conflictId||c['id']?.toString()==conflictId);await _saveConflicts(current);await _pullChanges();final resolved=r['conflict'];return resolved is Map?Map<String,dynamic>.from(resolved):r;}
  Future<void> syncNow() async{if(_syncing||_accessToken==null||_accessToken!.isEmpty)return;_syncing=true;try{await _ensureDevice();await _pushOutbox();await _pullChanges();await refreshConflicts();}finally{_syncing=false;}}
  Future<void> _pushOutbox() async{final items=await _outbox();if(items.isEmpty)return;final key=await _deviceKey();final r=await _request('/api/sync/push',method:'POST',body:{'deviceKey':key,'changes':items.take(200).toList()});final rawAccepted=r['accepted'];final accepted=rawAccepted is List?rawAccepted.map((e)=>Map<String,dynamic>.from(e as Map)).map((e)=>e['clientId']?.toString()).whereType<String>().toSet():<String>{};final rawConflicts=r['conflicts'];final conflicts=rawConflicts is List?rawConflicts.map((e)=>Map<String,dynamic>.from(e as Map)).toList():<Map<String,dynamic>>[];final conflictIds=conflicts.map((e)=>e['clientId']?.toString()).whereType<String>().toSet();if(conflicts.isNotEmpty){final saved=await _conflicts();for(final c in conflicts){final id=c['clientId']?.toString();final original=items.cast<Map<String,dynamic>?>().firstWhere((e)=>e?['clientId']?.toString()==id,orElse:()=>null);saved.add({...c,'localChange':original,'detectedAt':DateTime.now().toIso8601String()});}await _saveConflicts(saved);}await _saveOutbox(items.where((e){final id=e['clientId']?.toString();return id==null||(!accepted.contains(id)&&!conflictIds.contains(id));}).toList());}
  Future<void> _pullChanges() async{final p=_prefs??=await SharedPreferences.getInstance();final cursor=p.getInt(_cursorPref)??0;final key=await _deviceKey();final r=await _request('/api/sync/changes?deviceKey=${Uri.encodeQueryComponent(key)}&cursor=$cursor&limit=200');final raw=r['changes'];final changes=raw is List?raw.map((e)=>Map<String,dynamic>.from(e as Map)):<Map<String,dynamic>>[];for(final change in changes){final type=change['entity_type']??change['entityType'];final id=change['entity_id']??change['entityId'];if(type==null||id==null)continue;final name='$_cachePrefix$type:$id';if(change['operation']=='delete')await p.remove(name);else await p.setString(name,jsonEncode(change['payload']??{}));}final next=int.tryParse('${r['cursor']??cursor}')??cursor;if(next>=cursor)await p.setInt(_cursorPref,next);}
  Future<Map<String,dynamic>?> readCached(String entityType,String entityId) async{final p=_prefs??=await SharedPreferences.getInstance();final raw=p.getString('$_cachePrefix$entityType:$entityId');if(raw==null)return null;return Map<String,dynamic>.from(jsonDecode(raw) as Map);}
  Future<void> clearLocalSyncData() async{final p=_prefs??=await SharedPreferences.getInstance();await p.remove(_outboxPref);await p.remove(_cursorPref);await p.remove(_conflictsPref);for(final k in p.getKeys().where((k)=>k.startsWith(_cachePrefix)).toList())await p.remove(k);}
}