const { authenticate, requireRoles } = require('./auth');

function registerMobileDashboardRoutes(app, pool) {
  const adminRoles=['super_admin','principal','admin'];
  app.get('/api/portal/me/teacher-overview', authenticate, requireRoles('teacher'), async (req,res,next)=>{try{const {rows}=await pool.query(`SELECT ts.section_id AS "sectionId",c.name AS "className",s.name AS "sectionName",su.name AS "subjectName",COUNT(DISTINCT e.student_id)::int AS "studentCount" FROM teacher_subjects ts JOIN sections s ON s.id=ts.section_id AND s.school_id=ts.school_id JOIN classes c ON c.id=s.class_id AND c.school_id=ts.school_id JOIN subjects su ON su.id=ts.subject_id AND su.school_id=ts.school_id LEFT JOIN enrollments e ON e.section_id=ts.section_id AND e.school_id=ts.school_id AND e.status='active' WHERE ts.school_id=$1 AND ts.teacher_id=(SELECT id FROM teachers WHERE user_id=$2 AND school_id=$1 LIMIT 1) AND ($3::uuid IS NULL OR ts.branch_id=$3) GROUP BY ts.section_id,c.name,s.name,su.name ORDER BY c.name,s.name,su.name`,[req.auth.schoolId,req.auth.userId,req.auth.branchId||null]);res.json({sections:rows,studentCount:rows.reduce((n,r)=>n+Number(r.studentCount||0),0)});}catch(err){next(err);}});
  app.get('/api/portal/me/admin-overview', authenticate, requireRoles(...adminRoles), async (req,res,next)=>{try{const [students,teachers,attendance,fees]=await Promise.all([pool.query(`SELECT COUNT(*)::int n FROM students WHERE school_id=$1 AND status='active' AND ($2::uuid IS NULL OR branch_id=$2)`,[req.auth.schoolId,req.auth.branchId||null]),pool.query(`SELECT COUNT(*)::int n FROM teachers WHERE school_id=$1 AND status='active' AND ($2::uuid IS NULL OR branch_id=$2)`,[req.auth.schoolId,req.auth.branchId||null]),pool.query(`SELECT COALESCE(ROUND(100.0*COUNT(*) FILTER(WHERE status='present')/NULLIF(COUNT(*),0),1),0) n FROM attendance_records WHERE school_id=$1 AND attendance_date=CURRENT_DATE AND ($2::uuid IS NULL OR branch_id=$2)`,[req.auth.schoolId,req.auth.branchId||null]),pool.query(`SELECT COALESCE(SUM(balance_amount),0) n FROM fee_invoices WHERE school_id=$1 AND status IN ('open','partially_paid','overdue') AND ($2::uuid IS NULL OR branch_id=$2)`,[req.auth.schoolId,req.auth.branchId||null])]);res.json({stats:{studentCount:students.rows[0].n,teacherCount:teachers.rows[0].n,attendancePercent:Number(attendance.rows[0].n),outstanding:Number(fees.rows[0].n)}});}catch(err){next(err);}});
  app.get('/api/portal/me/student-overview', authenticate, requireRoles('student'), async (req,res,next)=>{try{const {rows}=await pool.query(`SELECT s.id,s.admission_no AS "admissionNo",s.full_name AS "fullName",s.photo_url AS "photoUrl",e.section_id AS "sectionId",c.name AS "className",sec.name AS "sectionName",COALESCE((SELECT SUM(GREATEST(0,fi.balance_amount)) FROM fee_invoices fi WHERE fi.school_id=s.school_id AND fi.student_id=s.id AND fi.status IN('unpaid','partial','open','partially_paid','overdue') AND ($3::uuid IS NULL OR fi.branch_id=$3 OR fi.branch_id IS NULL)),0) AS outstanding FROM student_portal_profiles p JOIN students s ON s.id=p.student_id AND s.school_id=p.school_id LEFT JOIN LATERAL(SELECT e.* FROM enrollments e WHERE e.student_id=s.id AND e.school_id=s.school_id AND e.status='active' ORDER BY e.created_at DESC NULLS LAST LIMIT 1)e ON true LEFT JOIN sections sec ON sec.id=e.section_id LEFT JOIN classes c ON c.id=sec.class_id WHERE p.school_id=$1 AND p.user_id=$2 AND p.status='active' AND s.status='active' LIMIT 1`,[req.auth.schoolId,req.auth.sub,req.auth.branchId||null]);if(!rows.length)return res.status(404).json({error:'Student profile not linked'});const student=rows[0];const a=await pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='present')::int present,COUNT(*) FILTER(WHERE status='absent')::int absent,COUNT(*) FILTER(WHERE status='late')::int late,COUNT(*) FILTER(WHERE status='half_day')::int half_day,COUNT(*) FILTER(WHERE status='leave')::int leave FROM attendance_records WHERE school_id=$1 AND student_id=$2 AND ($3::uuid IS NULL OR branch_id=$3 OR branch_id IS NULL)`,[req.auth.schoolId,student.id,req.auth.branchId||null]);const x=a.rows[0];const pct=Number(x.total)?Number(((Number(x.present)+Number(x.late)*.5+Number(x.half_day)*.5)/Number(x.total)*100).toFixed(2)):0;res.json({student,outstanding:Number(student.outstanding||0),attendance:{...x,attendancePercent:pct},homework:[]});}catch(err){next(err);}});
}
module.exports={registerMobileDashboardRoutes};
