const { authenticate, requireRoles } = require('./auth');

function registerReportCardRoutes(app, pool) {
  const staffRoles = ['super_admin','principal','admin','teacher'];

  async function getGrade(client, schoolId, branchId, percent) {
    const { rows } = await client.query(`SELECT grade FROM grade_scales WHERE school_id=$1 AND ($2::uuid IS NULL OR branch_id=$2 OR branch_id IS NULL) AND min_percent <= $3 AND max_percent >= $3 ORDER BY branch_id NULLS LAST,min_percent DESC LIMIT 1`, [schoolId, branchId || null, percent]);
    return rows[0]?.grade || null;
  }

  async function getTemplate(client, schoolId, branchId, templateId) {
    const { rows } = await client.query(`SELECT id,name,template_key AS "templateKey",branch_id AS "branchId",layout_json AS "layout",is_default AS "isDefault",is_active AS "isActive" FROM report_card_templates WHERE id=$1 AND school_id=$2 AND is_active=true AND ($3::uuid IS NULL OR branch_id=$3 OR branch_id IS NULL)`, [templateId, schoolId, branchId || null]);
    return rows[0] || null;
  }

  app.get('/api/report-card/templates', authenticate, async (req,res,next) => {
    try { const { rows } = await pool.query(`SELECT id,name,template_key AS "templateKey",branch_id AS "branchId",layout_json AS "layout",is_default AS "isDefault",is_active AS "isActive" FROM report_card_templates WHERE school_id=$1 AND is_active=true AND ($2::uuid IS NULL OR branch_id=$2 OR branch_id IS NULL) ORDER BY is_default DESC,name`, [req.auth.schoolId,req.auth.branchId||null]); res.json({ templates: rows }); } catch(err){ next(err); }
  });

  app.post('/api/report-card/templates', authenticate, requireRoles(...staffRoles), async (req,res,next) => {
    const client=await pool.connect(); try { const {name,templateKey='standard',layout={}}=req.body||{}; if(!name)return res.status(400).json({error:'name is required'}); const branchId=req.auth.branchId||null; await client.query('BEGIN'); if(req.body?.isDefault) await client.query(`UPDATE report_card_templates SET is_default=false,updated_at=now() WHERE school_id=$1 AND branch_id IS NOT DISTINCT FROM $2`,[req.auth.schoolId,branchId]); const {rows}=await client.query(`INSERT INTO report_card_templates (school_id,branch_id,name,template_key,layout_json,is_default) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id,name,template_key AS "templateKey",branch_id AS "branchId",layout_json AS "layout",is_default AS "isDefault"`,[req.auth.schoolId,branchId,String(name).trim(),String(templateKey).trim(),JSON.stringify(layout),Boolean(req.body?.isDefault)]); await client.query('COMMIT'); res.status(201).json({template:rows[0]}); } catch(err){await client.query('ROLLBACK').catch(()=>{});next(err);} finally{client.release();}
  });

  app.patch('/api/report-card/templates/:id', authenticate, requireRoles(...staffRoles), async (req,res,next) => {
    const client=await pool.connect(); try { const current=await client.query(`SELECT id,branch_id AS "branchId" FROM report_card_templates WHERE id=$1 AND school_id=$2 AND ($3::uuid IS NULL OR branch_id=$3 OR branch_id IS NULL)`,[req.params.id,req.auth.schoolId,req.auth.branchId||null]); if(!current.rowCount)return res.status(404).json({error:'Template not found'}); const templateBranch=current.rows[0].branchId; await client.query('BEGIN'); if(req.body?.isDefault) await client.query(`UPDATE report_card_templates SET is_default=false,updated_at=now() WHERE school_id=$1 AND branch_id IS NOT DISTINCT FROM $2`,[req.auth.schoolId,templateBranch]); const {rows}=await client.query(`UPDATE report_card_templates SET name=COALESCE($3,name),template_key=COALESCE($4,template_key),layout_json=COALESCE($5,layout_json),is_default=COALESCE($6,is_default),is_active=COALESCE($7,is_active),updated_at=now() WHERE id=$1 AND school_id=$2 RETURNING id,name,template_key AS "templateKey",branch_id AS "branchId",layout_json AS "layout",is_default AS "isDefault",is_active AS "isActive"`,[req.params.id,req.auth.schoolId,req.body?.name,req.body?.templateKey,req.body?.layout===undefined?null:JSON.stringify(req.body.layout),req.body?.isDefault,req.body?.isActive]); await client.query('COMMIT');res.json({template:rows[0]}); } catch(err){await client.query('ROLLBACK').catch(()=>{});next(err);} finally{client.release();}
  });

  app.get('/api/report-card/configs', authenticate, async (req,res,next) => {
    try { const {rows}=await pool.query(`SELECT c.id,c.name,c.session_id AS "sessionId",c.is_active AS "isActive",c.branch_id AS "branchId",c.template_id AS "templateId",COALESCE(json_agg(json_build_object('examTypeId',x.exam_type_id,'weightPercent',x.weight_percent,'displayOrder',x.display_order) ORDER BY x.display_order) FILTER (WHERE x.id IS NOT NULL),'[]'::json) AS components FROM report_card_configs c LEFT JOIN report_card_components x ON x.config_id=c.id WHERE c.school_id=$1 AND ($2::uuid IS NULL OR c.branch_id=$2) GROUP BY c.id ORDER BY c.name`,[req.auth.schoolId,req.auth.branchId||null]);res.json({configs:rows}); } catch(err){next(err);} });

  app.post('/api/report-card/configs', authenticate, requireRoles(...staffRoles), async (req,res,next) => {
    const client=await pool.connect(); try { const {sessionId,name,templateId=null,components=[]}=req.body||{}; if(!sessionId||!name||!Array.isArray(components)||!components.length)return res.status(400).json({error:'sessionId, name and components are required'}); const total=components.reduce((sum,c)=>sum+Number(c.weightPercent||0),0); if(Math.abs(total-100)>0.01)return res.status(400).json({error:'Report card component weights must total 100%'}); const branchId=req.auth.branchId||null; await client.query('BEGIN'); if(templateId){const t=await getTemplate(client,req.auth.schoolId,branchId,templateId);if(!t){await client.query('ROLLBACK');return res.status(404).json({error:'Template not found for this school or branch'});}} const cfg=await client.query(`INSERT INTO report_card_configs (school_id,branch_id,session_id,name,template_id) SELECT $1,$2,id,$3,$5 FROM academic_sessions WHERE id=$4 AND school_id=$1 RETURNING id,name,session_id AS "sessionId",branch_id AS "branchId",template_id AS "templateId"`,[req.auth.schoolId,branchId,String(name).trim(),sessionId,templateId]); if(!cfg.rowCount){await client.query('ROLLBACK');return res.status(404).json({error:'Academic session not found for this school'});} for(let i=0;i<components.length;i++){const c=components[i];if(!c.examTypeId||Number(c.weightPercent)<0){await client.query('ROLLBACK');return res.status(400).json({error:'Each component needs examTypeId and valid weightPercent'});}const result=await client.query(`INSERT INTO report_card_components (config_id,exam_type_id,weight_percent,display_order) SELECT $1,id,$3,$4 FROM exam_types WHERE id=$2 AND school_id=$5 AND ($6::uuid IS NULL OR branch_id=$6)`,[cfg.rows[0].id,c.examTypeId,Number(c.weightPercent),i+1,req.auth.schoolId,branchId]);if(!result.rowCount){await client.query('ROLLBACK');return res.status(404).json({error:'One or more exam types were not found for this school or branch'});}} await client.query('COMMIT');res.status(201).json({config:cfg.rows[0]}); }catch(err){await client.query('ROLLBACK').catch(()=>{});next(err);}finally{client.release();}
  });

  app.post('/api/report-card/generate/:studentId', authenticate, requireRoles(...staffRoles), async (req,res,next) => {
    const client=await pool.connect();
    try {
      const {sessionId,configId}=req.body||{}; if(!sessionId||!configId)return res.status(400).json({error:'sessionId and configId are required'});
      const branchId=req.auth.branchId||null; await client.query('BEGIN');
      const student=await client.query(`SELECT id,admission_no AS "admissionNo",full_name AS "fullName",branch_id AS "branchId" FROM students WHERE id=$1 AND school_id=$2 AND ($3::uuid IS NULL OR branch_id IS NULL OR branch_id=$3)`,[req.params.studentId,req.auth.schoolId,branchId]);
      if(!student.rowCount){await client.query('ROLLBACK');return res.status(404).json({error:'Student not found for this school or branch'});}
      const cfg=await client.query(`SELECT c.id,c.session_id AS "sessionId",c.branch_id AS "branchId",c.template_id AS "templateId",x.exam_type_id AS "examTypeId",x.weight_percent AS "weightPercent" FROM report_card_configs c JOIN report_card_components x ON x.config_id=c.id WHERE c.id=$1 AND c.school_id=$2 AND c.session_id=$3 AND ($4::uuid IS NULL OR c.branch_id=$4) ORDER BY x.display_order`,[configId,req.auth.schoolId,sessionId,branchId]);
      if(!cfg.rowCount){await client.query('ROLLBACK');return res.status(404).json({error:'Report card configuration not found'});}
      const existing=await client.query(`SELECT id,status FROM report_cards WHERE school_id=$1 AND session_id=$2 AND student_id=$3 AND ($4::uuid IS NULL OR branch_id=$4) FOR UPDATE`,[req.auth.schoolId,sessionId,req.params.studentId,branchId]);
      if(existing.rows[0]?.status==='published'){await client.query('ROLLBACK');return res.status(409).json({error:'Report card is already published. Create a new configuration/session result before regenerating.'});}
      const components=cfg.rows; const exams=await client.query(`SELECT e.id,e.exam_type_id AS "examTypeId",es.id AS "examSubjectId",es.subject_id AS "subjectId",es.max_marks AS "maxMarks",m.marks FROM exams e JOIN exam_subjects es ON es.exam_id=e.id LEFT JOIN exam_marks m ON m.exam_subject_id=es.id AND m.student_id=$1 AND m.school_id=$2 WHERE e.school_id=$2 AND e.session_id=$3 AND ($4::uuid IS NULL OR e.branch_id=$4) AND e.exam_type_id=ANY($5::uuid[]) ORDER BY es.subject_id`,[req.params.studentId,req.auth.schoolId,sessionId,branchId,components.map(x=>x.examTypeId)]);
      const bySubject=new Map(); for(const r of exams.rows){if(!bySubject.has(r.subjectId))bySubject.set(r.subjectId,[]);bySubject.get(r.subjectId).push(r);}
      const card=await client.query(`INSERT INTO report_cards (school_id,branch_id,session_id,student_id,config_id,status,total_marks,percentage) VALUES ($1,$2,$3,$4,$5,'draft',0,0) ON CONFLICT (school_id,session_id,student_id) DO UPDATE SET config_id=EXCLUDED.config_id,branch_id=EXCLUDED.branch_id,status='draft',generated_at=now() RETURNING id`,[req.auth.schoolId,branchId,sessionId,req.params.studentId,configId]);
      const cardId=card.rows[0].id; await client.query('DELETE FROM report_card_subjects WHERE report_card_id=$1',[cardId]); let grandPercentage=0,subjectCount=0,totalRawMarks=0;
      for(const [subjectId,rows] of bySubject){let weighted=0;let availableWeight=0;let totalRaw=0;for(const c of components){const r=rows.find(x=>x.examTypeId===c.examTypeId);if(r&&r.marks!==null&&Number(r.maxMarks)>0){const pct=Number(r.marks)/Number(r.maxMarks)*100;weighted+=pct*Number(c.weightPercent)/100;availableWeight+=Number(c.weightPercent);totalRaw+=Number(r.marks);}}const pct=availableWeight?weighted*100/availableWeight:0;const grade=await getGrade(client,req.auth.schoolId,branchId,pct);const s=await client.query(`INSERT INTO report_card_subjects (report_card_id,subject_id,total_marks,percentage,grade) VALUES ($1,$2,$3,$4,$5) RETURNING id`,[cardId,subjectId,totalRaw,pct,grade]);for(const c of components){const r=rows.find(x=>x.examTypeId===c.examTypeId);if(r){await client.query(`INSERT INTO report_card_exam_marks (report_card_subject_id,exam_type_id,marks,max_marks,weighted_marks) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (report_card_subject_id,exam_type_id) DO UPDATE SET marks=EXCLUDED.marks,max_marks=EXCLUDED.max_marks,weighted_marks=EXCLUDED.weighted_marks`,[s.rows[0].id,c.examTypeId,r.marks,r.maxMarks,r.marks===null?null:Number(r.marks)/Number(r.maxMarks)*Number(c.weightPercent)]);}}grandPercentage+=pct;subjectCount++;totalRawMarks+=totalRaw;}
      const percentage=subjectCount?grandPercentage/subjectCount:0;const overallGrade=await getGrade(client,req.auth.schoolId,branchId,percentage);await client.query(`UPDATE report_cards SET total_marks=$2,percentage=$3,overall_grade=$4,generated_at=now() WHERE id=$1`,[cardId,totalRawMarks,percentage,overallGrade]); await client.query('COMMIT');res.status(201).json({reportCardId:cardId,status:'draft',percentage:Number(percentage.toFixed(2)),overallGrade,templateId:components[0].templateId||null});
    }catch(err){await client.query('ROLLBACK').catch(()=>{});next(err);}finally{client.release();}
  });

  app.get('/api/report-card/:id', authenticate, async (req,res,next) => {
    try {
      const branchId=req.auth.branchId||null;
      const {rows}=await pool.query(`SELECT rc.id,rc.status,rc.session_id AS "sessionId",rc.student_id AS "studentId",rc.config_id AS "configId",rc.branch_id AS "branchId",rc.total_marks AS "totalMarks",rc.percentage,rc.overall_grade AS "overallGrade",rc.generated_at AS "generatedAt",s.admission_no AS "admissionNo",s.full_name AS "fullName",c.name AS "configName",c.template_id AS "templateId",a.name AS "sessionName",COALESCE(b.name,'School') AS "branchName" FROM report_cards rc JOIN students s ON s.id=rc.student_id JOIN report_card_configs c ON c.id=rc.config_id LEFT JOIN academic_sessions a ON a.id=rc.session_id LEFT JOIN branches b ON b.id=rc.branch_id WHERE rc.id=$1 AND rc.school_id=$2 AND ($3::uuid IS NULL OR rc.branch_id=$3 OR rc.branch_id IS NULL)`,[req.params.id,req.auth.schoolId,branchId]);
      if(!rows.length)return res.status(404).json({error:'Report card not found for this school or branch'});
      const card=rows[0];
      const template=card.templateId?await getTemplate(pool,req.auth.schoolId,branchId,card.templateId):null;
      const subjects=await pool.query(`SELECT rcs.id,rcs.subject_id AS "subjectId",sub.name AS "subjectName",rcs.total_marks AS "totalMarks",rcs.percentage,rcs.grade,rcs.remarks,COALESCE(json_agg(json_build_object('examTypeId',m.exam_type_id,'examType',et.code,'marks',m.marks,'maxMarks',m.max_marks,'weightedMarks',m.weighted_marks) ORDER BY et.display_order) FILTER (WHERE m.id IS NOT NULL),'[]'::json) AS exams FROM report_card_subjects rcs JOIN subjects sub ON sub.id=rcs.subject_id LEFT JOIN report_card_exam_marks m ON m.report_card_subject_id=rcs.id LEFT JOIN exam_types et ON et.id=m.exam_type_id WHERE rcs.report_card_id=$1 GROUP BY rcs.id,sub.name ORDER BY sub.name`,[card.id]);
      const school=await pool.query(`SELECT id,name,code FROM schools WHERE id=$1`,[req.auth.schoolId]);
      res.json({reportCard:card,school:school.rows[0]||null,template,subjects:subjects.rows});
    }catch(err){next(err);}
  });

  app.post('/api/report-card/:id/publish', authenticate, requireRoles('super_admin','principal','admin'), async(req,res,next)=>{try{const {rows}=await pool.query(`UPDATE report_cards SET status='published' WHERE id=$1 AND school_id=$2 AND ($3::uuid IS NULL OR branch_id=$3) AND status='draft' RETURNING id,status,percentage,overall_grade AS "overallGrade"`,[req.params.id,req.auth.schoolId,req.auth.branchId||null]);if(!rows.length)return res.status(404).json({error:'Draft report card not found for this school or branch'});res.json({reportCard:rows[0]});}catch(err){next(err);}});

  app.get('/api/report-card/student/:studentId', authenticate, async (req,res,next) => {
    try { const {sessionId}=req.query;if(!sessionId)return res.status(400).json({error:'sessionId is required'});const student=await pool.query(`SELECT id,admission_no AS "admissionNo",full_name AS "fullName",branch_id AS "branchId" FROM students WHERE id=$1 AND school_id=$2 AND ($3::uuid IS NULL OR branch_id IS NULL OR branch_id=$3)`,[req.params.studentId,req.auth.schoolId,req.auth.branchId||null]);if(!student.rowCount)return res.status(404).json({error:'Student not found for this school or branch'});const {rows}=await pool.query(`SELECT sub.id AS "subjectId",sub.name AS "subjectName",t.code AS "examType",m.marks,m.grade,es.max_marks AS "maxMarks" FROM subjects sub JOIN exam_subjects es ON es.subject_id=sub.id JOIN exams e ON e.id=es.exam_id AND e.session_id=$2 AND e.school_id=$1 AND ($4::uuid IS NULL OR e.branch_id=$4) JOIN exam_types t ON t.id=e.exam_type_id LEFT JOIN exam_marks m ON m.exam_subject_id=es.id AND m.student_id=$3 AND ($4::uuid IS NULL OR m.branch_id=$4) WHERE sub.school_id=$1 AND ($4::uuid IS NULL OR es.branch_id=$4) ORDER BY sub.name,t.display_order`,[req.auth.schoolId,sessionId,req.params.studentId,req.auth.branchId||null]);res.json({student:student.rows[0],sessionId,marks:rows}); }catch(err){next(err);}
  });
}
module.exports={registerReportCardRoutes};
